Repository lirantal/cypress-social-logins, pull requests merged in 2020-10, with the labels that each got.

#59 feat: export baseLoginConnect function
  src/Plugins.js
Labels: enhancement, hacktoberfest

#60 Documentation custom login
  README.md
Labels: enhancement

#61 fix: 🐛 baseLoginConnect is not defined error
  src/Plugins.js
Labels: hacktoberfest, hacktoberfest-accepted
